#!/usr/bin/env python3
"""Generate AngelScript catalog hints from exported Virtools metadata JSON."""

from __future__ import annotations

import argparse
import json
import keyword
import re
from pathlib import Path
from typing import Any, Iterable


def read_json_array(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8-sig")
    if not text.strip():
        return []
    data = json.loads(text)
    if data is None:
        return []
    if isinstance(data, list):
        return [item for item in data if isinstance(item, dict)]
    return [data] if isinstance(data, dict) else []


def u32(value: Any) -> int:
    return int(value) & 0xFFFFFFFF


def hex_u32(value: Any) -> str:
    return f"0x{u32(value):08x}"


def guid_parts(item: dict[str, Any]) -> tuple[str, str]:
    guid = item.get("guid")
    if isinstance(guid, list) and len(guid) >= 2:
        return hex_u32(guid[0]), hex_u32(guid[1])

    guid_hex = item.get("guid_hex")
    if isinstance(guid_hex, str):
        match = re.fullmatch(r"0x([0-9a-fA-F]+)-0x([0-9a-fA-F]+)", guid_hex)
        if match:
            return f"0x{match.group(1)}", f"0x{match.group(2)}"

    return "0x00000000", "0x00000000"


def guid_expr(item: dict[str, Any]) -> str:
    first, second = guid_parts(item)
    return f"CKGUID({first}, {second})"


AS_RESERVED = {
    "and",
    "auto",
    "bool",
    "break",
    "case",
    "cast",
    "class",
    "const",
    "continue",
    "default",
    "do",
    "else",
    "enum",
    "false",
    "float",
    "for",
    "funcdef",
    "if",
    "import",
    "in",
    "inout",
    "int",
    "interface",
    "is",
    "mixin",
    "namespace",
    "null",
    "or",
    "out",
    "private",
    "return",
    "shared",
    "super",
    "switch",
    "this",
    "true",
    "uint",
    "void",
    "while",
    "xor",
}


def identifier(name: Any, used: set[str]) -> str:
    text = re.sub(r"[^A-Za-z0-9_]", "_", str(name or "")).strip("_")
    if not text:
        text = "Item"
    if text[0].isdigit():
        text = f"_{text}"
    if text in AS_RESERVED or keyword.iskeyword(text):
        text = f"_{text}"

    base = text
    suffix = 2
    while text in used:
        text = f"{base}_{suffix}"
        suffix += 1
    used.add(text)
    return text


def add_guid_function(lines: list[str], name: str, item: dict[str, Any]) -> None:
    lines.append(f"    CKGUID {name}() {{ return {guid_expr(item)}; }}")


def value_items(params: Iterable[dict[str, Any]], category: str) -> Iterable[dict[str, Any]]:
    for param in params:
        if param.get("category") == category and isinstance(param.get("values"), list):
            yield param


def generate(params: list[dict[str, Any]], ops: list[dict[str, Any]], bbs: list[dict[str, Any]]) -> str:
    lines: list[str] = [
        "// Generated by tools/generate_angelscript_catalog.py.",
        "// Edit the source JSON or regenerate this file instead of editing by hand.",
        "",
        "namespace CKASCatalog {",
    ]

    lines.append("namespace ParamTypes {")
    used_param_names: set[str] = set()
    for param in params:
        add_guid_function(lines, identifier(param.get("name"), used_param_names), param)
    lines.append("}")
    lines.append("")

    lines.append("namespace Enums {")
    used_enum_type_names: set[str] = set()
    for param in value_items(params, "enum"):
        type_name = identifier(param.get("name"), used_enum_type_names)
        used_value_names: set[str] = set()
        lines.append(f"namespace {type_name} {{")
        for value in param["values"]:
            lines.append(f"    const int {identifier(value.get('name'), used_value_names)} = {int(value.get('value', 0))};")
        lines.append("}")
    lines.append("}")
    lines.append("")

    lines.append("namespace Flags {")
    used_flags_type_names: set[str] = set()
    for param in value_items(params, "flags"):
        type_name = identifier(param.get("name"), used_flags_type_names)
        used_value_names: set[str] = set()
        lines.append(f"namespace {type_name} {{")
        for value in param["values"]:
            lines.append(f"    const uint {identifier(value.get('name'), used_value_names)} = {hex_u32(value.get('value', 0))};")
        lines.append("}")
    lines.append("}")
    lines.append("")

    lines.append("namespace Operations {")
    used_op_names: set[str] = set()
    for op in ops:
        add_guid_function(lines, identifier(op.get("name"), used_op_names), op)
    lines.append("}")
    lines.append("")

    lines.append("namespace BBs {")
    used_bb_names: set[str] = set()
    for bb in bbs:
        category = str(bb.get("category") or "")
        name = str(bb.get("name") or "")
        qualified = name if not category else f"{category}_{name}"
        add_guid_function(lines, identifier(qualified, used_bb_names), bb)
    lines.append("}")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    default_validation_dir = root / "build" / "validation" / "ballance"

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--validation-dir", type=Path, default=default_validation_dir)
    parser.add_argument("--params-json", type=Path)
    parser.add_argument("--ops-json", type=Path)
    parser.add_argument("--bbs-json", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    params_json = args.params_json or args.validation_dir / "params.json"
    ops_json = args.ops_json or args.validation_dir / "ops.json"
    bbs_json = args.bbs_json or args.validation_dir / "bbs.json"
    output = args.output or args.validation_dir / "CKAngelScriptCatalog.as"

    params = read_json_array(params_json)
    ops = read_json_array(ops_json)
    bbs = read_json_array(bbs_json)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generate(params, ops, bbs), encoding="utf-8")

    print(json.dumps({
        "params": len(params),
        "operations": len(ops),
        "building_blocks": len(bbs),
        "output": str(output.resolve()),
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
