#!/usr/bin/env python3
"""Generate AngelScript catalog hints from exported Virtools metadata JSON."""

from __future__ import annotations

import argparse
import json
import keyword
import re
from pathlib import Path
from typing import Any, Iterable


def read_json_array(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8-sig")
    if not text.strip():
        return []
    data = json.loads(text)
    if data is None:
        return []
    if isinstance(data, list):
        return [item for item in data if isinstance(item, dict)]
    return [data] if isinstance(data, dict) else []


def u32(value: Any) -> int:
    return int(value) & 0xFFFFFFFF


def hex_u32(value: Any) -> str:
    return f"0x{u32(value):08x}"


def guid_parts(item: dict[str, Any]) -> tuple[str, str]:
    guid = item.get("guid")
    if isinstance(guid, list) and len(guid) >= 2:
        return hex_u32(guid[0]), hex_u32(guid[1])

    guid_hex = item.get("guid_hex")
    if isinstance(guid_hex, str):
        match = re.fullmatch(r"0x([0-9a-fA-F]+)-0x([0-9a-fA-F]+)", guid_hex)
        if match:
            return f"0x{match.group(1)}", f"0x{match.group(2)}"

    return "0x00000000", "0x00000000"


def guid_expr(item: dict[str, Any]) -> str:
    first, second = guid_parts(item)
    return f"CKGUID({first}, {second})"


def as_string(value: Any) -> str:
    text = str(value or "")
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\r", "\\r").replace("\n", "\\n") + '"'


AS_RESERVED = {
    "and",
    "auto",
    "bool",
    "break",
    "case",
    "cast",
    "class",
    "const",
    "continue",
    "default",
    "do",
    "else",
    "enum",
    "false",
    "float",
    "for",
    "funcdef",
    "if",
    "import",
    "in",
    "inout",
    "int",
    "interface",
    "is",
    "mixin",
    "namespace",
    "null",
    "or",
    "out",
    "private",
    "return",
    "shared",
    "super",
    "switch",
    "this",
    "true",
    "uint",
    "void",
    "while",
    "xor",
}


def identifier(name: Any, used: set[str]) -> str:
    text = re.sub(r"[^A-Za-z0-9_]", "_", str(name or "")).strip("_")
    if not text:
        text = "Item"
    if text[0].isdigit():
        text = f"_{text}"
    if text in AS_RESERVED or keyword.iskeyword(text):
        text = f"_{text}"

    base = text
    suffix = 2
    while text in used:
        text = f"{base}_{suffix}"
        suffix += 1
    used.add(text)
    return text


def add_guid_function(lines: list[str], name: str, item: dict[str, Any]) -> None:
    lines.append(f"    CKGUID {name}() {{ return {guid_expr(item)}; }}")


def bb_qualified_name(item: dict[str, Any]) -> str:
    category = str(item.get("category") or "")
    name = str(item.get("name") or "")
    return name if not category else f"{category}/{name}"


def bb_slot_items(item: dict[str, Any], key: str) -> list[str]:
    values = item.get(key)
    if isinstance(values, list):
        result: list[str] = []
        for value in values:
            if isinstance(value, str):
                result.append(value)
            elif isinstance(value, dict):
                result.append(str(value.get("name") or ""))
        return result
    return []


def add_bb_slot_helpers(lines: list[str], bb: dict[str, Any]) -> None:
    slot_specs = [
        ("In", "inputs"),
        ("Out", "outputs"),
        ("Pin", "input_params"),
        ("Pout", "output_params"),
        ("Setting", "settings"),
        ("Local", "local_params"),
    ]
    for method, key in slot_specs:
        used_names: set[str] = set()
        for name in bb_slot_items(bb, key):
            function_name = identifier(name or f"{method}Slot", used_names)
            lines.append(f"    BBSlot@ {method}_{function_name}(const CKBehaviorContext &in ctx) {{ BBDecl@ decl = Decl(ctx); return decl is null ? null : decl.{method}({as_string(name)}); }}")


def value_items(params: Iterable[dict[str, Any]], category: str) -> Iterable[dict[str, Any]]:
    for param in params:
        if param.get("category") == category and isinstance(param.get("values"), list):
            yield param


def generate(params: list[dict[str, Any]], ops: list[dict[str, Any]], bbs: list[dict[str, Any]]) -> str:
    lines: list[str] = [
        "// Generated by tools/generate_angelscript_catalog.py.",
        "// Edit the source JSON or regenerate this file instead of editing by hand.",
        "",
        "namespace CKASCatalog {",
    ]

    lines.append("namespace ParamTypes {")
    used_param_names: set[str] = set()
    for param in params:
        add_guid_function(lines, identifier(param.get("name"), used_param_names), param)
    lines.append("}")
    lines.append("")

    lines.append("namespace Enums {")
    used_enum_type_names: set[str] = set()
    for param in value_items(params, "enum"):
        type_name = identifier(param.get("name"), used_enum_type_names)
        used_value_names: set[str] = set()
        lines.append(f"namespace {type_name} {{")
        lines.append(f"    CKGUID Type() {{ return {guid_expr(param)}; }}")
        lines.append("    ParamTypeInfo@ Info(const CKBehaviorContext &in ctx) { return Param::Type(ctx, Type()); }")
        lines.append("    string Text(const CKBehaviorContext &in ctx, int value) { return Param::Text(ctx, Type(), value); }")
        for value in param["values"]:
            lines.append(f"    const int {identifier(value.get('name'), used_value_names)} = {int(value.get('value', 0))};")
        lines.append("}")
    lines.append("}")
    lines.append("")

    lines.append("namespace Flags {")
    used_flags_type_names: set[str] = set()
    for param in value_items(params, "flags"):
        type_name = identifier(param.get("name"), used_flags_type_names)
        used_value_names: set[str] = set()
        lines.append(f"namespace {type_name} {{")
        lines.append(f"    CKGUID Type() {{ return {guid_expr(param)}; }}")
        lines.append("    ParamTypeInfo@ Info(const CKBehaviorContext &in ctx) { return Param::Type(ctx, Type()); }")
        lines.append("    string Text(const CKBehaviorContext &in ctx, uint value) { return Param::Text(ctx, Type(), value); }")
        lines.append("    uint Mask(const CKBehaviorContext &in ctx, const string &in namesOrMask) { return Param::FlagsMask(ctx, Type(), namesOrMask); }")
        for value in param["values"]:
            lines.append(f"    const uint {identifier(value.get('name'), used_value_names)} = {hex_u32(value.get('value', 0))};")
        lines.append("}")
    lines.append("}")
    lines.append("")

    lines.append("namespace Operations {")
    used_op_names: set[str] = set()
    for op in ops:
        add_guid_function(lines, identifier(op.get("name"), used_op_names), op)
    lines.append("}")
    lines.append("")

    lines.append("namespace OperationHints {")
    used_op_hint_names: set[str] = set()
    for op in ops:
        op_name = identifier(op.get("name"), used_op_hint_names)
        lines.append(f"namespace {op_name} {{")
        lines.append(f"    CKGUID Guid() {{ return {guid_expr(op)}; }}")
        lines.append("    ParamOp@ Create(const CKBehaviorContext &in ctx) { return Param::Operation(ctx, Guid()); }")
        lines.append("}")
    lines.append("}")
    lines.append("")

    lines.append("namespace BBs {")
    used_bb_names: set[str] = set()
    for bb in bbs:
        category = str(bb.get("category") or "")
        name = str(bb.get("name") or "")
        qualified = name if not category else f"{category}_{name}"
        add_guid_function(lines, identifier(qualified, used_bb_names), bb)
    lines.append("}")
    lines.append("")

    lines.append("namespace BBHints {")
    used_bb_hint_names: set[str] = set()
    for bb in bbs:
        category = str(bb.get("category") or "")
        name = str(bb.get("name") or "")
        qualified = bb_qualified_name(bb)
        hint_name = identifier(qualified.replace("/", "_"), used_bb_hint_names)
        lines.append(f"namespace {hint_name} {{")
        lines.append(f"    CKGUID Guid() {{ return {guid_expr(bb)}; }}")
        lines.append(f"    const string Name = {as_string(name)};")
        lines.append(f"    const string Category = {as_string(category)};")
        lines.append(f"    const string QualifiedName = {as_string(qualified)};")
        lines.append("    BBPrototype@ Find(const CKBehaviorContext &in ctx) { return BB::Prototype(ctx, Guid()); }")
        lines.append("    BBDecl@ Decl(const CKBehaviorContext &in ctx) { return BB::Require(ctx, Guid()); }")
        lines.append("    BBConfig@ Config(const CKBehaviorContext &in ctx) { return BB::Bind(ctx, Guid()); }")
        add_bb_slot_helpers(lines, bb)
        lines.append("}")
    lines.append("}")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    default_validation_dir = root / "build" / "validation" / "ballance"

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--validation-dir", type=Path, default=default_validation_dir)
    parser.add_argument("--params-json", type=Path)
    parser.add_argument("--ops-json", type=Path)
    parser.add_argument("--bbs-json", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    params_json = args.params_json or args.validation_dir / "params.json"
    ops_json = args.ops_json or args.validation_dir / "ops.json"
    bbs_json = args.bbs_json or args.validation_dir / "bbs.json"
    output = args.output or args.validation_dir / "CKAngelScriptCatalog.as"

    params = read_json_array(params_json)
    ops = read_json_array(ops_json)
    bbs = read_json_array(bbs_json)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generate(params, ops, bbs), encoding="utf-8")

    print(json.dumps({
        "params": len(params),
        "operations": len(ops),
        "building_blocks": len(bbs),
        "output": str(output.resolve()),
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
