#ifndef CKAS_VERSION_H
#define CKAS_VERSION_H

#define CKAS_VERSION_MAJOR 0
#define CKAS_VERSION_MINOR 1
#define CKAS_VERSION_PATCH 0
#define CKAS_VERSION_TWEAK 0
#define CKAS_VERSION "0.1.0.0"

#endif // CKAS_VERSION_H
